# Generated by Django 5.2.8 on 2025-12-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_address_users_default_donation_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
