# Generated by Django 5.2.8 on 2026-01-25 19:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_profile_image_users_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_image_upload_path),
        ),
    ]
