# Generated by Django 5.2.8 on 2026-01-25 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Card', 'Card'), ('PayPal', 'PayPal')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
