# Generated by Django 5.2.8 on 2026-02-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userpaymentaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
