# Generated by Django 5.2.8 on 2025-11-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
