# Generated by Django 5.2.8 on 2025-11-30 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_ratings_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
