# Generated by Django 5.2.8 on 2026-05-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('DARSA', 'Darsa'), ('DUA', 'Dua'), ('INSPIRATION', 'Daily Inspiration'), ('KHUTBA', 'Juma Khutba')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('author_or_sheikh', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When should this be shown? (e.g., Darsa time)', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
