# Generated by Django 5.2.5 on 2026-08-12 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Image or icon key', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Dua Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('arabic_text', models.TextField()),
                ('transliteration', models.TextField(blank=True, null=True)),
                ('translation_en', models.TextField()),
                ('translation_sw', models.TextField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duas', to='duas.duacategory')),
            ],
            options={
                'ordering': ['category', 'display_order', 'title'],
            },
        ),
    ]
