# Generated by Django 5.2.8 on 2026-01-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
