# Generated by Django 5.2.8 on 2026-01-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donations_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='DonationImage',
        ),
    ]
