# Generated by Django 5.2.8 on 2026-01-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donations_image_urls_delete_donationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
    ]
