# Generated by Django 5.2.8 on 2026-01-21 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0006_alter_donations_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donations",
            name="account_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="donations",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="donations",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donations",
            name="paybill_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="donations",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="donations",
            name="target_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
