# Generated by Django 5.2.8 on 2026-01-22 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0007_alter_donations_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donations",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="donations",
            name="account_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="donations",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="donations",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="donations",
            name="paybill_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="donations",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="donations",
            name="target_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
