# Generated by Django 5.2.8 on 2026-02-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_donations_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
