# Generated by Django 5.2.8 on 2026-01-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
