# Generated by Django 5.2.8 on 2026-01-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactions_mpesa_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('M-Pesa', 'M-Pesa'), ('Paypal', 'Paypal'), ('Flutterwave', 'Flutterwave')], max_length=50),
        ),
    ]
