# Generated by Django 5.2.8 on 2026-01-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactions_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('M-Pesa', 'M-Pesa'), ('Paypal', 'Paypal')], max_length=50),
        ),
    ]
