# Generated by Django 5.2.5 on 2026-08-12 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quran/reciters/')),
            ],
        ),
        migrations.CreateModel(
            name='SurahAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField(help_text='1 to 114')),
                ('audio_url', models.URLField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('reciter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surah_audios', to='quran.reciter')),
            ],
            options={
                'ordering': ['surah_number', 'reciter__name'],
                'unique_together': {('surah_number', 'reciter')},
            },
        ),
    ]
