"""
Django settings for JMCDonations project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""
# At the bottom of settings.py, after all other imports
from firebase_admin import credentials
import json
from datetime import datetime, timedelta
from pathlib import Path
import firebase_admin
import os
from dotenv import load_dotenv
# dj_database_url is optional; install 'python-dj-database-url' if you need it.
# import dj_database_url
from decouple import config
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
# SERVICE_ACCOUNT_KEY_PATH = os.path.join(BASE_DIR, 'config/jmcdonations.json')
# cred = credentials.Certificate(SERVICE_ACCOUNT_KEY_PATH)
# firebase_admin.initialize_app(cred, {
#     'projectId': 'jmcdonations-cd458' 
# })
# Initialize the credentials object

# SECURITY WARNING: don't run with debug turned on in production!
# Render-specific settings

DEBUG = True
# DEBUG = config('DEBUG', default=False, cast=bool)
# Database
# dj_database_url-based configuration removed because the package may not be installed;
# the project uses the later sqlite DATABASES default defined further below.
# To enable DATABASE_URL parsing, install 'python-dj-database-url' and restore this block.

ALLOWED_HOSTS = [
    "jmcdonations.onrender.com",
    "www.khalfanathman.site",
    "khalfanathman.site",
    "localhost", "127.0.0.1",
    "diatomaceous-preventively-amber.ngrok-free.dev"
    "jmc-admin-dashboard.vercel.app",
    "192.168.3.96"
    ]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", 
    "http://127.0.0.1:3000",
    "https://jmcdonations.onrender.com",
    "https://khalfanathman.site",
    "https://www.khalfanathman.site",
    "https://jmc-admin-dashboard.vercel.app",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # CORS
    "corsheaders",
    "whitenoise.runserver_nostatic",

    # Third-party apps
    "rest_framework",
    "djoser",
    "drf_yasg",
    "oauth2_provider",
    "social_django",
    "drf_social_oauth2",
    "silk",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "django_filters",
    "django_crontab",
    'django_celery_results',
    'django_celery_beat',
    # Local apps
    "users",
    "donations",
    "analytics",
    "ratings",
    "categories",
    "transactions",
    "storages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "silk.middleware.SilkyMiddleware",
]

ROOT_URLCONF = "JMCDonations.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "JMCDonations.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        'OPTIONS': {
            'timeout': 30,
            'check_same_thread': False, 
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "users.Users"

# DRF Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "JMCDonations.authentication.FirebaseAuthentication",
        "rest_framework.authentication.SessionAuthentication", 
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "drf_social_oauth2.authentication.SocialAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        # "rest_framework.permissions.IsAuthenticated",
    ],
    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M:%S",
    'DATETIME_INPUT_FORMATS': ["%Y-%m-%dT%H:%M:%S", "iso-8601"],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
        ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
# Cron jobs configuration
CRONJOBS = [
    # Run every hour to clean up M-Pesa pending transactions
    ('0 * * * *', 'transactions.management.commands.cleanup_expired_transactions'),
    
    # Run daily at 2 AM to clean up all expired transactions
    ('0 2 * * *', 'transactions.management.commands.cleanup_expired_transactions'),

    # Run every hour to close expired donations
    ('0 * * * *', 'donations.management.commands.close_expired_donations'),
]
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # ... other Simple JWT settings
}
# Djoser Configuration
DJOSER = {
    "LOGIN_FIELD": "email",
    "USER_CREATE_PASSWORD_RETYPE": True,
    "SERIALIZERS": {
        "user_create": "users.serializers.UserCreateSerializer",
        "user": "users.serializers.UserSerializer",
        "current_user": "users.serializers.UserSerializer",
    },
}
# Spectacular Settings
SPECTACULAR_SETTINGS = {
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}
# Authentication Backends
AUTHENTICATION_BACKENDS = (
    # Social Auth
    "social_core.backends.google.GoogleOAuth2",
    "social_core.backends.facebook.FacebookAppOAuth2",
    "drf_social_oauth2.backends.DjangoOAuth2",
    # Firebase
    "authentication.backends.FirebaseBackend",
    # Django
    "django.contrib.auth.backends.ModelBackend",
)

# Social Auth Config (Stubs)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "google-client-id"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "google-client-secret"
SOCIAL_AUTH_FACEBOOK_KEY = "facebook-app-id"
SOCIAL_AUTH_FACEBOOK_SECRET = "facebook-app-secret"

# Swagger Settings
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"}
    }
}

# Daraja API Settings
MPESA_CONSUMER_KEY = os.getenv("MPESA_CONSUMER_KEY", "")
MPESA_CONSUMER_SECRET = os.getenv("MPESA_CONSUMER_SECRET", "")
MPESA_API_URL = os.getenv(
    "MPESA_API_URL", "https://sandbox.safaricom.co.ke"
)  # Use 'https://api.safaricom.co.ke' for production
MPESA_PASSKEY = os.getenv("MPESA_PASSKEY", "")
MPESA_SHORTCODE = os.getenv("MPESA_SHORTCODE", "")
# MPESA_CALLBACK_URL = os.getenv(
#     "MPESA_CALLBACK_URL", "https://jmc.com/api/transactions/callback/"
# )

MPESA_CALLBACK_URL = os.getenv(
    "MPESA_CALLBACK_URL", "https://diatomaceous-preventively-amber.ngrok-free.dev/api/v1/mpesa/callback/"
)

# PAYPAL
PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID", "")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET", "")
PAYPAL_MODE = os.getenv("PAYPAL_MODE", "sandbox")
PAYPAL_WEBHOOK_ID = os.getenv("PAYPAL_WEBHOOK_ID", "")
PAYPAL_CALLBACK_URL = os.getenv(
    "PAYPAL_CALLBACK_URL", "https://diatomaceous-preventively-amber.ngrok-free.dev/api/v1/transactions/paypal_callback/"
)
FIREBASE_API_KEY = os.getenv("FIREBASE_API_KEY")

try:
    # Check if Firebase is already initialized
    if not firebase_admin._apps:
        service_account_json = os.environ.get('FIREBASE_SERVICE_ACCOUNT_JSON')
        
        if service_account_json:
            try:
                data = json.loads(service_account_json)
                
                # Fix private key newlines
                if 'private_key' in data and '\\n' in data['private_key']:
                    data['private_key'] = data['private_key'].replace('\\n', '\n')
                
                cred = credentials.Certificate(data)
                firebase_admin.initialize_app(cred)
                print("✅ Firebase initialized successfully from environment variable")
            except Exception as e:
                print(f"❌ Firebase initialization failed: {e}")
        else:
            print("⚠️ FIREBASE_SERVICE_ACCOUNT_JSON not found")
    else:
        print("✅ Firebase already initialized (by another module)")
        
except Exception as e:
    print(f"⚠️ Firebase setup error: {e}")

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Default Redis URL
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'
CELERY_ENABLE_UTC = True

# Beat scheduler for periodic tasks
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Optional: Task settings
CELERY_TASK_ALWAYS_EAGER = False  # Set to True for local testing (no broker needed)
CELERY_TASK_EAGER_PROPAGATES = True
# AWS S3 Configuration
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'jmcdonations')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False

# Default file storage (Django 4.2+)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

