# Generated by Django 5.2.5 on 2026-08-12 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='PrayerCalculationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_method', models.CharField(choices=[('MUSLIM_WORLD_LEAGUE', 'Muslim World League'), ('ISLAMIC_SOCIETY_OF_NORTH_AMERICA', 'ISLAMIC_SOCIETY_OF_NORTH_AMERICA'), ('EGYPTIAN', 'Egyptian General Authority of Survey'), ('UMM_AL_QURA', 'Umm Al-Qura University, Makkah'), ('GULF', 'Gulf Region'), ('MOONSIGHTING_COMMITTEE', 'Moonsighting Committee Worldwide'), ('NORTH_AMERICA', 'North America (ISNA)'), ('KUWAIT', 'Kuwait'), ('QATAR', 'Qatar'), ('SINGAPORE', 'Majlis Ugama Islam Singapura, Singapore'), ('TEHRAN', 'Institute of Geophysics, University of Tehran'), ('TURKEY', 'Diyanet İşleri Başkanlığı, Turkey'), ('OTHER', 'Other')], default='MUSLIM_WORLD_LEAGUE', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Prayer Calculation Settings',
            },
        ),
        migrations.CreateModel(
            name='PrayerTimeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prayer_name', models.CharField(max_length=50)),
                ('overridden_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='prayer_times.city')),
            ],
            options={
                'unique_together': {('city', 'date', 'prayer_name')},
            },
        ),
    ]
